# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a7568c928c077968e994211a79ce0e98447dbb3bdccebb616358df4f7f34e91299e07a804d44865440b6be3c30d74bea88847d23639dc2739fd0ae8a4361f6b

test:
  secret_key_base: 938c14edddd57f54fe0792653f15954dc130981d1e4c394c691bf20dde96e900227f33dd95f7cbf766a7c115d9433f23c1e5ddb75464fa590e41cb99e079b232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
